USE [SHOPMANAGER]
GO

/****** Object:  Table [dbo].[TB_CLINIC]    Script Date: 2024-09-02 오후 2:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_CLINIC](
	[CLINIC_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLINIC_NAME] [varchar](50) NULL,
	[PRICE] [int] NULL,
	[USE_YN] [bit] NULL,
 CONSTRAINT [PK_TB_CLINIC] PRIMARY KEY CLUSTERED 
(
	[CLINIC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TB_MEMBER]    Script Date: 2024-09-02 오후 2:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_MEMBER](
	[MEMBER_ID] [int] IDENTITY(1,1) NOT NULL,
	[MEMBER_NAME] [varchar](50) NULL,
	[TELNO] [varchar](50) NULL,
	[ADDRESS] [varchar](250) NULL,
	[ETC] [varchar](max) NULL,
 CONSTRAINT [PK_TB_MEMBER] PRIMARY KEY CLUSTERED 
(
	[MEMBER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TB_PRODUCT]    Script Date: 2024-09-02 오후 2:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_PRODUCT](
	[PRODUCT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCT_NAME] [varchar](50) NULL,
	[PRICE] [int] NULL,
	[USE_YN] [bit] NULL,
 CONSTRAINT [PK_TB_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TB_SALE]    Script Date: 2024-09-02 오후 2:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_SALE](
	[SALE_ID] [int] IDENTITY(1,1) NOT NULL,
	[MEMBER_ID] [int] NULL,
	[SALE_DT] [char](10) NULL,
	[SALE_AMT] [int] NULL,
 CONSTRAINT [PK_TB_SALE] PRIMARY KEY CLUSTERED 
(
	[SALE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TB_SALE_PRODUCT]    Script Date: 2024-09-02 오후 2:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_SALE_PRODUCT](
	[SALE_ID] [int] NOT NULL,
	[PRODUCT_NAME] [varchar](50) NULL,
	[PRICE] [int] NULL,
	[QTY] [int] NULL
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TB_WORK]    Script Date: 2024-09-02 오후 2:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_WORK](
	[WORK_ID] [int] IDENTITY(1,1) NOT NULL,
	[MEMBER_ID] [int] NULL,
	[WORK_DT] [char](10) NULL,
	[WORK_AMT] [int] NULL,
 CONSTRAINT [PK_TB_WORK] PRIMARY KEY CLUSTERED 
(
	[WORK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TB_WORK_CLINIC]    Script Date: 2024-09-02 오후 2:44:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_WORK_CLINIC](
	[WORK_ID] [int] NOT NULL,
	[CLINIC_NAME] [varchar](50) NULL,
	[PRICE] [int] NULL,
	[QTY] [int] NULL
) ON [PRIMARY]
GO

